openapi: 3.0.0
info:
  title: Social App
  description: our first social app at LCO - Adarsh
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v1
    description: Localhost version of our app
  - url: https://localhost:4000/api/v1
    description: this is just a dummy api url,it doesn't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer

